### ISSUE TITLE
Can't reproduce the result shown in paper

### ISSUE THREAD

**Issue by HyuanTan** [amitshaked/resmatch#14]
Hi, thanks for share. 
I use `th main.lua -ds kitti -a test -gpu 1 -mc resmatch -m fast` to predict the disparity map, but it seems there are something wrong with the results:

real.png:
![kitti2015_0_real](https://user-images.githubusercontent.com/14145396/38082158-652503b4-3378-11e8-96af-65cb7bf36073.png)

err.png:
![kitti2015_0_err](https://user-images.githubusercontent.com/14145396/38082179-79c7ad3a-3378-11e8-915c-9f9a7afcc18d.png)

gt.png:
![kitti2015_0_gt](https://user-images.githubusercontent.com/14145396/38082185-7f4861be-3378-11e8-8aca-90e92eccd880.png)

pred.png:
![kitti2015_0_pred](https://user-images.githubusercontent.com/14145396/38082196-884482b6-3378-11e8-86a3-a746e3772f2d.png)

Are there something wrong with my test parameter? Could you please give me some advices?
Thanks!

**Comment by gcaffaratti** [comment]
Hi @HyuanTan, I've figured out. You need to provide some trained parameters to the network, otherwise you are predicting over a random weight architecture. Download the pretrained model provided under the pretrained folder:

[Resmatch-Kitti2012-Fast](https://www.mediafire.com/?9fvwnimchbtdb27)

Then run the submit (or test) mode of the application, but providing the pretrained models:

`th main.lua -ds kitti -a submit -m fast -mc resmatch -mcnet ../pretrained/Resmatch-Kitti2012-Fast/mc/kitti_resmatch_fast_LL_rgb_all_net.t7 -dispnet ../pretrained/Resmatch-Kitti2012-Fast/disparity/net_reflective_kitti_resmatch_fast_LL_rgb_all_net.t7`

_Note:_ The command should be executed in the `src` folder and the pretrained models are under the `pretrained/Resmatch-Kitti2012-Fast`.

**Comment by HyuanTan** [comment]
@gcaffaratti Thanks! I thought it would read models from the default path and didn't set the `-mcnet` model path and `-dispnet` model path. According to your advice, the results seem normal.
